## Q 2: Write the function to generate random numbers from a normal distribution with mean 0 and **variance** 1.

In [ ]:
import numpy as np
def generate_random_numbers(n):
    random_numbers = np.random.normal(loc=0, scale=1, size=n)
    return random_numbers


## Q 3: Create a 1D array arr1 with 10 elements.
## (a) Slice this array starting from 3rd value to the end.
## (b) What is the result if you perform the following slicing on the given array. arr1[-4:-2]

In [ ]:
arr1 = np.random.randint(0,10,10)
print(arr1)

[4 3 1 7 9 1 5 0 5 9]


In [ ]:
arr1[3:11]

array([7, 9, 1, 5, 0, 5, 9])

In [ ]:
arr1[-4:-2]

array([5, 0])

## Q 4: Create two numpy arrays of size 4 x 4. Write functions used to calculate determinant of matrix, transpose of a matrix, norm of a matrix and to perform matrix multiplication. Write all the results.

In [ ]:
import numpy as np

# Create two 4x4 arrays
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

B = np.array([[16, 15, 14, 13],
              [12, 11, 10, 9],
              [8, 7, 6, 5],
              [4, 3, 2, 1]])


In [ ]:
def calculate_determinant(matrix):
    return np.linalg.det(matrix)


def calculate_transpose(matrix):
    return np.transpose(matrix)


def calculate_norm(matrix):
    return np.linalg.norm(matrix)


def perform_matrix_multiplication(matrix1, matrix2):
    return np.matmul(matrix1, matrix2)


In [ ]:
# Calculate determinant of matrix A
det_A = calculate_determinant(A)
print(f"Determinant of A: {det_A}\n")

det_B = calculate_determinant(B)
print(f"Determinant of B: {det_B}\n")

# Calculate transpose of matrix B
transpose_A = calculate_transpose(A)
print(f"Transpose of A:\n{transpose_A}\n")

transpose_B = calculate_transpose(B)
print(f"Transpose of B:\n{transpose_B}\n")

# Calculate norm of matrix A
norm_A = calculate_norm(A)
print(f"Norm of A: {norm_A}\n")

norm_B = calculate_norm(B)
print(f"Norm of B: {norm_B}\n")

# Perform matrix multiplication between matrices A and B
matrix_multiplication_AB = perform_matrix_multiplication(A, B)
print(f"Matrix multiplication of A and B:\n{matrix_multiplication_AB}\n")


Determinant of A: 0.0

Determinant of B: 0.0

Transpose of A:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Transpose of B:
[[16 12  8  4]
 [15 11  7  3]
 [14 10  6  2]
 [13  9  5  1]]

Norm of A: 38.67815921162743

Norm of B: 38.67815921162743

Matrix multiplication of A and B:
[[ 80  70  60  50]
 [240 214 188 162]
 [400 358 316 274]
 [560 502 444 386]]



## Q 6: Show and compare the results generated by PorterStemmer and WordNetLemmatizer on any sample tweet from twitter dataset.

In [ ]:
#First, we'll need to download the nltk library and the punkt and wordnet resources. 
import nltk

nltk.download('omw-1.4')
nltk.download('punkt')
nltk.download('wordnet')


[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
tweet = "Just saw a really cute cat video on YouTube. Can't stop smiling 😻 #cats #cutenessoverload"


In [ ]:
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize

# Initialize the stemmer and lemmatizer
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

# Tokenize the tweet into words
words = word_tokenize(tweet)

# Apply stemming to the words
stemmed_words = [stemmer.stem(word) for word in words]

# Apply lemmatization to the words
lemmatized_words = [lemmatizer.lemmatize(word) for word in words]


In [ ]:
print("Original tweet: ", tweet)
print("Stemmed tweet: ", " ".join(stemmed_words))
print("Lemmatized tweet: ", " ".join(lemmatized_words))


Original tweet:  Just saw a really cute cat video on YouTube. Can't stop smiling 😻 #cats #cutenessoverload
Stemmed tweet:  just saw a realli cute cat video on youtub . ca n't stop smile 😻 # cat # cutenessoverload
Lemmatized tweet:  Just saw a really cute cat video on YouTube . Ca n't stop smiling 😻 # cat # cutenessoverload
