# 1_NB_Classifier_Weather



In [ ]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB


In [ ]:
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']
temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild']
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No']


In [ ]:
le = preprocessing.LabelEncoder()
weather_encoded=le.fit_transform(weather)
print("Weather:" ,weather_encoded)


Weather: [2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [ ]:
temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)
print("Temp:",temp_encoded)
print("Play:",label)

Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [ ]:
#Combinig weather and temp into single listof tuples
features=tuple(zip(weather_encoded,temp_encoded))
print("Features:",features)


Features: ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [ ]:
#Create a Classifier
model=MultinomialNB()
# Train the model using the training sets
model.fit(features,label)

MultinomialNB()

In [ ]:
predicted= model.predict([[0,2]]) # 0:Overcast, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


In [ ]:
predicted= model.predict([[0,1]]) # 0:Overcast, 1:Hot
print("Predicted Value:", predicted)


Predicted Value: [1]


In [ ]:
predicted= model.predict([[2,2]]) # 2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


###Exercise:



In [ ]:
f=tuple(zip(temp_encoded,weather_encoded))
print("Features:",f)

#Create a Classifier
model=MultinomialNB()

# Train the model
model.fit(f,label)


Features: ((1, 2), (1, 2), (1, 0), (2, 1), (0, 1), (0, 1), (0, 0), (2, 2), (0, 2), (2, 1), (2, 2), (2, 0), (1, 0), (2, 1))


MultinomialNB()

### 1.5.1 Will you play if the temperature is ‘Hot’ and weather is ‘overcast’?

In [ ]:
predicted = model.predict([[1,0]]) 
print("Predicted Value:", predicted)

Predicted Value: [1]


### 1.5.1 Will you play if the temperature is ‘Mild’ and weather is ‘Sunny’?

In [ ]:
predicted = model.predict([[2,2]]) 
print("Predicted Value:", predicted)

Predicted Value: [1]


#2_NB_Classifier_Iris_2Classes

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
iris = datasets.load_iris()

In [ ]:
# print the names of the 13 features
print("Features: ", iris.feature_names)
# print the label type of wine(class_0, class_1, class_2)
print("Labels: ", iris.target_names)
# print data(feature)shape
print("\nData shape: ",iris.data.shape)
#print data(target)shape
print("\nTraget shape: ",iris.target.shape)
print("\nData: ",iris.data)
print("\nTarget: ",iris.target)
print("\nData type: ",type(iris.data))
newdata = iris.data[50:,:]
newtarget = iris.target[50:]
# print data(feature)shape
print("\nNew Data shape: ",newdata.shape)
#print data(target)shape
print("\nNew Traget shape: ",newtarget.shape)

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']

Data shape:  (150, 4)

Traget shape:  (150,)

Data:  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2

In [ ]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(newdata,newtarget, test_size = 0.30, random_state = 5)

In [ ]:
import numpy as np
gnb = GaussianNB()

gnb.fit(data_train, target_train)

target_pred = gnb.predict(data_test)

In [ ]:
from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.9


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[16,  1],
       [ 2, 11]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: 0.8888888888888888
recall: 0.9411764705882353


#3_NB_Classifier_Iris_3Classes

In [ ]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
iris = datasets.load_iris()

In [ ]:
print("Features: ", iris.feature_names)
print("Labels: ", iris.target_names)
iris.data.shape

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']


(150, 4)

In [ ]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(iris.data,iris.target, test_size = 0.30, random_state = 10)

In [ ]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)

In [ ]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 1.0


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 14]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1. 1. 1.]
recall: [1. 1. 1.]


## Exercise:


## 26<=Rollnumber<=50: 
## Task 1: Try the algo on Dataset1 - LabelEncoding of features:
and Train test Division 80%-20%

In [ ]:
from sklearn.naive_bayes import GaussianNB
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [ ]:
datasets = pd.read_csv('Dataset1.csv')
print(datasets)

   Outlook Temp Humidity Wind Play
0        R    H   Normal    F    N
1        R    H     High    T    N
2        O    H   Normal    F    Y
3        S    M   Normal    F    Y
4        S    C   Normal    F    Y
5        S    C      Low    T    N
6        O    C   Normal    T    Y
7        R    M   Normal    F    N
8        R    C      Low    F    Y
9        S    M     High    F    Y
10       R    M     High    T    Y
11       O    M      Low    T    Y
12       O    H   Normal    F    Y
13       S    M   Normal    T    N


In [ ]:
X = datasets.iloc[ : ,:-1].values
Y = datasets.iloc[ : ,-1].values
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])
datasets.iloc[:,:-1] = X[:,:]
X[:,1] = le.fit_transform(X[:,1])
datasets.iloc[:,:-1] = X[:,:]
X[:,2] = le.fit_transform(X[:,2])
datasets.iloc[:,:-1] = X[:,:]
X[:,3] = le.fit_transform(X[:,3])
print(X)
datasets.iloc[:,:-1] = X[:,:]
print(datasets.head())

[[1 1 2 0]
 [1 1 0 1]
 [0 1 2 0]
 [2 2 2 0]
 [2 0 2 0]
 [2 0 1 1]
 [0 0 2 1]
 [1 2 2 0]
 [1 0 1 0]
 [2 2 0 0]
 [1 2 0 1]
 [0 2 1 1]
 [0 1 2 0]
 [2 2 2 1]]
  Outlook Temp Humidity Wind Play
0       1    1        2    0    N
1       1    1        0    1    N
2       0    1        2    0    Y
3       2    2        2    0    Y
4       2    0        2    0    Y


In [ ]:
outlook_enc = X[:,0]
print(outlook_enc)

[1 1 0 2 2 2 0 1 1 2 1 0 0 2]


In [ ]:
temp_enc = X[:,1]
print(temp_enc)

[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [ ]:
humidity_enc = X[:,2]
print(humidity_enc)

[2 0 2 2 2 1 2 2 1 0 0 1 2 2]


In [ ]:
wind_enc = X[:,3]
print(wind_enc)

[0 1 0 0 0 1 1 0 0 0 1 1 0 1]


In [ ]:
le = preprocessing.LabelEncoder()
target_enc = le.fit_transform(datasets['Play'])
print(target_enc)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [ ]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(X,
Y, test_size = 0.80, random_state = 2) #Random State is last two digits of my id


In [ ]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)

In [ ]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.4166666666666667


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)


array([[1, 3],
       [4, 4]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.2        0.57142857]
recall: [0.25 0.5 ]


In [ ]:
features=tuple(zip(outlook_enc,temp_enc,humidity_enc,wind_enc))
print("Features:",features)
model=MultinomialNB()
model.fit(features,target_enc)



Features: ((1, 1, 2, 0), (1, 1, 0, 1), (0, 1, 2, 0), (2, 2, 2, 0), (2, 0, 2, 0), (2, 0, 1, 1), (0, 0, 2, 1), (1, 2, 2, 0), (1, 0, 1, 0), (2, 2, 0, 0), (1, 2, 0, 1), (0, 2, 1, 1), (0, 1, 2, 0), (2, 2, 2, 1))


MultinomialNB()

### What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?

In [ ]:
predicted = model.predict([[1,2,2,0]])
print("Predicted Value:", predicted)

Predicted Value: [1]


### What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’, and Wind = ’True’?

In [ ]:
predicted = model.predict([[2,0,0,1]])
print("Predicted Value:", predicted)

Predicted Value: [0]


## 26<=Rollnumber<=50: 
## Task 2: Apply algorithm on breast cancer wisconsin dataset - One Hot Encoding of features: and Train test Division 60%-40%

In [ ]:
from sklearn import datasets
data=datasets.load_breast_cancer()
data.target
data.keys()
data_train, data_test, target_train, target_test = train_test_split(iris.data, iris.target, test_size = 0.6, random_state = 2)
from sklearn import metrics
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)
accuracy = metrics.accuracy_score(target_test, target_pred)
print('Accuracy: {}'.format(accuracy))
precision = metrics.precision_score(target_test, target_pred, average=None)
print('Precision: {}'.format(precision))
recall = metrics.recall_score(target_test, target_pred, average=None)
print('Recall: {}'.format(recall))

Accuracy: 0.9555555555555556
Precision: [1.         0.9        0.96296296]
Recall: [1.         0.96428571 0.89655172]
